# Generated by Django 5.1.1 on 2025-11-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_job_posting_duration_max_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_posting',
            name='application_deadline',
            field=models.DateTimeField(blank=True, help_text='Optional deadline (date & time). After this time applications will be closed.', null=True),
        ),
    ]
